name: theme_extensionable
description: A theme extension macros
version: 0.1.0+1


environment:
  sdk: ">=3.5.0-0.0-dev <4.0.0"
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  data_class:
    git: https://github.com/ManIlya/data_class.git
  macros: ^0.1.0-main.5
  macro_util: ^0.1.0-11.dev
dependency_overrides:
  collection: ^1.19.0
